import React from "react";
import { ListItemButton, ListItemIcon, ListItemText } from "@mui/material";
import importModels from "../backend/modelTransfer/importModels";
import { ImportExport } from "@mui/icons-material";

const ImportModels = () => {
  return (
    <ListItemButton onClick={importModels}>
      <ListItemIcon>
        <ImportExport />
      </ListItemIcon>
      <ListItemText
        primary="Import Models"
        secondary="Choose models folder generated by the export models. May need to restart the app to see the changes"
      />
    </ListItemButton>
  );
};

export default ImportModels;
