name: Build
on: [push]

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 22
      - name: install yarn
        run: npm install -g yarn
      - name: install dependencies
        run: yarn install
      - name: build
        run: yarn make

  build_on_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 22
      - name: install yarn
        run: npm install -g yarn
      - name: install dependencies
        run: yarn install
      - name: build
        run: yarn make
